# Generated by Django 6.0.1 on 2026-01-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('players_count', models.PositiveSmallIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('balance', models.PositiveSmallIntegerField()),
                ('catastrophe', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bio', 'Биологические данные'), ('health', 'Здоровье'), ('hobby', 'Увлечения'), ('phobia', 'Фобия'), ('character', 'Характер'), ('background', 'Прошлое'), ('knowledge', 'Знание'), ('item', 'Предметы')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('power', models.IntegerField(help_text='Negative = bad, positive = good')),
                ('difficulty_weight', models.PositiveSmallIntegerField(default=3)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveSmallIntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('device_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.room')),
            ],
            options={
                'unique_together': {('room', 'seat')},
            },
        ),
    ]
