# Generated by Django 6.0.1 on 2026-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='difficulty_weight',
        ),
        migrations.AlterField(
            model_name='trait',
            name='power',
            field=models.IntegerField(help_text='Отрицательное значение - что-то плохое. Положительное - что-то хорошее. От -10 до 10'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.PositiveSmallIntegerField(default=1, help_text='От 1 до 10'),
        ),
    ]
