# Generated by Django 6.0.1 on 2026-01-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_trait_difficulty_weight_alter_trait_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='is_active',
        ),
    ]
