# Generated by Django 6.0.1 on 2026-01-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trait_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_revealed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_traits', to='main.player')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.trait')),
            ],
            options={
                'unique_together': {('player', 'trait')},
            },
        ),
    ]
