# Generated by Django 6.0.1 on 2026-01-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignedtrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveSmallIntegerField(help_text='От 1 до 5')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(help_text='От 1 до 3 (не кол-во мест!)')),
                ('difficulty', models.PositiveSmallIntegerField(help_text='От 1 до 5 (чем больше - тем сложнее)')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='catastrophe',
            new_name='severity',
        ),
        migrations.AlterUniqueTogether(
            name='assignedtrait',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trait',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='type',
        ),
        migrations.AddField(
            model_name='assignedtrait',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedtrait',
            name='trait_type',
            field=models.CharField(choices=[('bio', 'Биологические данные'), ('profession', 'Профессия'), ('health', 'Здоровье'), ('hobby', 'Увлечения'), ('fear', 'Страх'), ('character', 'Характер'), ('background', 'Прошлое'), ('knowledge', 'Знание'), ('item', 'Предметы')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trait',
            name='trait_type',
            field=models.CharField(choices=[('bio', 'Биологические данные'), ('profession', 'Профессия'), ('health', 'Здоровье'), ('hobby', 'Увлечения'), ('fear', 'Страх'), ('character', 'Характер'), ('background', 'Прошлое'), ('knowledge', 'Знание'), ('item', 'Предметы')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomCatastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.catastrophe')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catastrophe', to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='main.room')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.shelterdescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignedtrait',
            name='trait',
        ),
    ]
