# Generated by Django 6.0.1 on 2026-01-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catastrophe_shelterdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='rarity',
        ),
    ]
