# Generated by Django 6.0.1 on 2026-01-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_trait_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcatastrophe',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_catastrophe', to='main.room'),
        ),
    ]
