# Generated by Django 6.0.1 on 2026-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_roomcatastrophe_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
