# Generated by Django 6.0.1 on 2026-01-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_player_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtrait',
            options={'ordering': ['trait_type']},
        ),
    ]
