# Generated by Django 6.0.1 on 2026-01-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_assignedtrait_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReactionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignedActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actioncard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_cards', to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedReactionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_cards', to='main.player')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reactioncard')),
            ],
        ),
    ]
