# Generated by Django 6.0.1 on 2026-01-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_actioncard_reactioncard_assignedactioncard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedactioncard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='assignedreactioncard',
            name='card',
        ),
        migrations.AddField(
            model_name='assignedactioncard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedreactioncard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedactioncard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card', to='main.player'),
        ),
        migrations.AlterField(
            model_name='assignedreactioncard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_card', to='main.player'),
        ),
    ]
