# Generated by Django 6.0.1 on 2026-01-17 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_assignedactioncard_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedactioncard',
            name='card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.actioncard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedreactioncard',
            name='card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.reactioncard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedactioncard',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_card', to='main.player'),
        ),
        migrations.AlterField(
            model_name='assignedreactioncard',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_card', to='main.player'),
        ),
    ]
