# Generated by Django 6.0.1 on 2026-01-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_assignedactioncard_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedactioncard',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_card', to='main.player'),
        ),
        migrations.AlterField(
            model_name='assignedreactioncard',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_card', to='main.player'),
        ),
    ]
