# Generated by Django 6.0.1 on 2026-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_assignedactioncard_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='started_at',
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
